ASPNET.MVC.UntukPemula/Pegawai.Web/Models/Karyawan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegawai.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karyawan
    {
        public string NIP { get; set; }
        public int DivisiID { get; set; }
        public string Nama { get; set; }
        public string Alamat { get; set; }
        public Nullable<System.DateTime> TanggalLahir { get; set; }
        public virtual Divisi Divisi { get; set; }
    }
}

ASPNET.MVC.UntukPemula/Pegawai.Web/Models/KaryawanViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
//default system
using System.Threading.Tasks;

namespace Pegawai.Web.Models //directory tempat penyimpan class ada di Pegawai.web/models
{
    public class KaryawanViewModel
    {
        // defaulnya kosong
        public string NIP { get; set; }
        public string NamaPegawai { get; set; }
        public string Nama { get; set; }
        public string Alamat { get; set; }
        public DateTime TanggalLahir { get; set; }
        //public = di publicasikan ke project, datatime = type colom table, tanggallahir=nama kolom table


    }

}

ASPNET.MVC.UntukPemula/Pegawai.Web/Controllers/KaryawansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Pegawai.Web.Models;

namespace Pegawai.Web.Controllers
{
    public class KaryawansController : Controller
    {
        private PegawaiDBEntities db = new PegawaiDBEntities();

        // GET: Karyawans
        public ActionResult Index()
        {
            var karyawans = db.Karyawans.Include(k => k.Divisi);
            return View(karyawans.ToList());
        }

        // GET: Karyawans/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Karyawan karyawan = db.Karyawans.Find(id);
            if (karyawan == null)
            {
                return HttpNotFound();
            }
            return View(karyawan);
        }

        // GET: Karyawans/Create
        public ActionResult Create()
        {
            ViewBag.DivisiID = new SelectList(db.Divisis, "DivisiID", "NamaDivisi");
            return View();
        }

        // POST: Karyawans/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NIP,DivisiID,Nama,Alamat,TanggalLahir")] Karyawan karyawan)
        {
            if (ModelState.IsValid)
            {
                db.Karyawans.Add(karyawan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DivisiID = new SelectList(db.Divisis, "DivisiID", "NamaDivisi", karyawan.DivisiID);
            return View(karyawan);
        }

        // GET: Karyawans/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Karyawan karyawan = db.Karyawans.Find(id);
            if (karyawan == null)
            {
                return HttpNotFound();
            }
            ViewBag.DivisiID = new SelectList(db.Divisis, "DivisiID", "NamaDivisi", karyawan.DivisiID);
            return View(karyawan);
        }

        // POST: Karyawans/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NIP,DivisiID,Nama,Alamat,TanggalLahir")] Karyawan karyawan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(karyawan).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DivisiID = new SelectList(db.Divisis, "DivisiID", "NamaDivisi", karyawan.DivisiID);
            return View(karyawan);
        }

        // GET: Karyawans/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Karyawan karyawan = db.Karyawans.Find(id);
            if (karyawan == null)
            {
                return HttpNotFound();
            }
            return View(karyawan);
        }

        // POST: Karyawans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Karyawan karyawan = db.Karyawans.Find(id);
            db.Karyawans.Remove(karyawan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ASPNET.MVC.UntukPemula/Pegawai.Web/Views/Karyawans/Create.cshtml
@model Pegawai.Web.Models.Karyawan

@{
    ViewBag.Title = "Management Karyawan";
}


<div class="row-fluid sortable">

    <div class="box span12">

        <div class="box-header" data-original-title>
            <h2>
                <i class="halflings-icon user"></i><span class="break"></span><i class="halflings-icon wrench"></i>
                @Html.ActionLink("Kembali", "Index")
            </h2>
            <div class="box-icon">
                <a href="#" class="btn-setting">
                    <i class="halflings-icon wrench"></i>
                </a>
                <a href="#" class="btn-minimize">
                    <i class="halflings-icon chevron-up"></i>
                </a>
                <a href="#" class="btn-close">
                    <i class="halflings-icon remove"></i>
                </a>
            </div>
        </div>

        <div class="box-content">
            <!-- <table class="table table-striped table-boardered bootstrap-datatable datatable">-->
            @using (Html.BeginForm("Create", "Karyawans", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <fieldset>
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="control-group">
                        @Html.LabelFor(model => model.NIP, htmlAttributes: new { @class = "control-label" })
                        <div class="controls">
                            @Html.EditorFor(model => model.NIP, new { htmlAttributes = new { @class = "span6 typeahead" } })
                            @Html.ValidationMessageFor(model => model.NIP, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="control-group">
                        @Html.LabelFor(model => model.DivisiID, htmlAttributes: new { @class = "control-label" })
                        <div class="controls">
                            @Html.DropDownList("DivisiID", null, htmlAttributes: new { @class = "span6 typeahead" })
                            @Html.ValidationMessageFor(model => model.DivisiID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="control-group">
                        @Html.LabelFor(model => model.Nama, htmlAttributes: new { @class = "control-label" })
                        <div class="controls">
                            @Html.EditorFor(model => model.Nama, new { htmlAttributes = new { @class = "span6 typeahead" } })
                            @Html.ValidationMessageFor(model => model.Nama, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="control-group">
                        @Html.LabelFor(model => model.Alamat, htmlAttributes: new { @class = "control-label" })
                        <div class="controls">
                            @Html.EditorFor(model => model.Alamat, new { htmlAttributes = new { @class = "span6 typeahead" } })
                            @Html.ValidationMessageFor(model => model.Alamat, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="control-group">
                        @Html.LabelFor(model => model.TanggalLahir, htmlAttributes: new { @class = "control-label" })
                        <div class="controls">
                            @Html.EditorFor(model => model.TanggalLahir, new { htmlAttributes = new { @class = "input-xlarge datepicker" } })
                            @Html.ValidationMessageFor(model => model.TanggalLahir, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary">
                            Simpan
                        </button>
                    </div>
                </fieldset>
            }

            <!--sampai sini-->

        </div>
    </div>
</div>
@*@{
        ViewBag.Title = "Create";
    }

    <h2>Create</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Karyawan</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.NIP, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NIP, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NIP, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DivisiID, "DivisiID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("DivisiID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DivisiID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Nama, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nama, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nama, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Alamat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Alamat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Alamat, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TanggalLahir, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TanggalLahir, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TanggalLahir, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
*@

ASPNET.MVC.UntukPemula/Pegawai.Web/Views/Karyawans/Delete.cshtml
@model Pegawai.Web.Models.Karyawan


@{
    ViewBag.Title = "Management Karyawan";
}


<div class="row-fluid sortable">

    <div class="box span12">

        <div class="box-header" data-original-title>
            <h2>
                <i class="halflings-icon user"></i><span class="break"></span><i class="halflings-icon wrench"></i>
                @Html.ActionLink("Kembali", "Index")
            </h2>
            <div class="box-icon">
                <a href="#" class="btn-setting">
                    <i class="halflings-icon wrench"></i>
                </a>
                <a href="#" class="btn-minimize">
                    <i class="halflings-icon chevron-up"></i>
                </a>
                <a href="#" class="btn-close">
                    <i class="halflings-icon remove"></i>
                </a>
            </div>
        </div>

        <div class="box-content">
            <!-- <table class="table table-striped table-boardered bootstrap-datatable datatable">-->
            @using (Html.BeginForm("Delete", "Karyawans", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <fieldset>
                    @Html.AntiForgeryToken()
                    <h3>Apakah benar data ini akan di hapus?</h3>

                    <div class="control-group">
                        @Html.LabelFor(model => model.Nama, htmlAttributes: new { @class = "control-label" })
                        <div class="controls">
                            <span class="input-xlarge uneditable-input">
                                @Html.DisplayFor(model => model.Nama)
                            </span>
                        </div>
                    </div>

                    <div class="control-group">
                        @Html.LabelFor(model => model.Alamat, htmlAttributes: new { @class = "control-label" })
                        <div class="controls">
                            <span class="input-xlarge uneditable-input">
                                @Html.DisplayFor(model => model.Alamat)
                            </span>
                        </div>
                    </div>

                    <div class="control-group">
                        @Html.LabelFor(model => model.TanggalLahir, htmlAttributes: new { @class = "control-label" })
                        <div class="controls">
                            <span class="input-xlarge uneditable-input">
                                @Html.DisplayFor(model => model.TanggalLahir)
                            </span>
                        </div>
                    </div>

                    <div class="control-group">
                        @Html.LabelFor(model => model.Divisi.NamaDivisi, htmlAttributes: new { @class = "control-label" })
                        <div class="controls">
                            <span class="input-xlarge uneditable-input">
                                @Html.DisplayFor(model => model.Divisi.NamaDivisi)
                            </span>
                        </div>
                    </div>

                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary">
                            Hapus
                        </button>
                    </div>
                </fieldset>
            }

            <!--sampai sini-->

        </div>
    </div>
</div>

@*@{
        ViewBag.Title = "Delete";
    }

    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Karyawan</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nama)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nama)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Alamat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Alamat)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TanggalLahir)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TanggalLahir)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Divisi.NamaDivisi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Divisi.NamaDivisi)
            </dd>

        </dl>

        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
*@

ASPNET.MVC.UntukPemula/Pegawai.Web/Views/Karyawans/Details.cshtml
@model Pegawai.Web.Models.Karyawan

@{
    ViewBag.Title = "Management Karyawan";
}


<div class="row-fluid sortable">

    <div class="box span12">

        <div class="box-header" data-original-title>
            <h2>
                <i class="halflings-icon user"></i><span class="break"></span><i class="halflings-icon wrench"></i>
                @Html.ActionLink("Kembali", "Index")
            </h2>
            <div class="box-icon">
                <a href="#" class="btn-setting">
                    <i class="halflings-icon wrench"></i>
                </a>
                <a href="#" class="btn-minimize">
                    <i class="halflings-icon chevron-up"></i>
                </a>
                <a href="#" class="btn-close">
                    <i class="halflings-icon remove"></i>
                </a>
            </div>
        </div>

        <div class="box-content">
            <!-- <table class="table table-striped table-boardered bootstrap-datatable datatable">-->
            @using (Html.BeginForm("Details", "Karyawans", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <fieldset>
                    @Html.AntiForgeryToken()
                    <h3>Details</h3>
                                        
                    <div class="control-group">
                        @Html.LabelFor(model => model.Nama, htmlAttributes: new { @class = "control-label" })
                        <div class="controls">
                            <span class="input-xlarge uneditable-input">
                                @Html.DisplayFor(model => model.Nama)
                            </span>
                        </div>
                    </div>

                    <div class="control-group">
                        @Html.LabelFor(model => model.Alamat, htmlAttributes: new { @class = "control-label" })
                        <div class="controls">
                            <span class="input-xlarge uneditable-input">
                                @Html.DisplayFor(model => model.Alamat)
                            </span>
                        </div>
                    </div>

                    <div class="control-group">
                        @Html.LabelFor(model => model.TanggalLahir, htmlAttributes: new { @class = "control-label" })
                        <div class="controls">
                            <span class="input-xlarge uneditable-input">
                                @Html.DisplayFor(model => model.TanggalLahir)
                            </span>
                        </div>
                    </div>

                    <div class="control-group">
                        @Html.LabelFor(model => model.Divisi.NamaDivisi, htmlAttributes: new { @class = "control-label" })
                        <div class="controls">
                            <span class="input-xlarge uneditable-input">
                                @Html.DisplayFor(model => model.Divisi.NamaDivisi)
                            </span>
                        </div>
                    </div>
                    
                    <div class="form-actions">
                        <button class="btn btn-primary">
                            @Html.ActionLink("Edit", "Edit", new { id = Model.NIP })
                        </button>
                    </div>
                </fieldset>
            }

            <!--sampai sini-->

        </div>
    </div>
</div>
@*
    @{
        ViewBag.Title = "Details";
    }

    <h2>Details</h2>

    <div>
        <h4>Karyawan</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nama)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nama)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Alamat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Alamat)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TanggalLahir)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TanggalLahir)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Divisi.NamaDivisi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Divisi.NamaDivisi)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.NIP }) |
        @Html.ActionLink("Back to List", "Index")
    </p>

*@

ASPNET.MVC.UntukPemula/Pegawai.Web/Views/Karyawans/Edit.cshtml
@model Pegawai.Web.Models.Karyawan

@{
    ViewBag.Title = "Management Karyawan";
}



<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2>
                <i class="halflings-icon user"></i><span class="break"></span><i class="halflings-icon th-list"></i>
                @Html.ActionLink("Kembali", "Index")
            </h2>
            <div class="box-icon">
                <a href="#" class="btn-setting">
                    <i class="halflings-icon wrench"></i>
                </a>
                <a href="#" class="btn-minimize">
                    <i class="halflings-icon chevron-up"></i>
                </a>
                <a href="#" class="btn-close">
                    <i class="halflings-icon remove"></i>
                </a>
            </div>
        </div>
        <div class="box-content">
            <!-- <table class="table table-striped table-boardered bootstrap-datatable datatable">-->
            @using (Html.BeginForm("Edit", "Karyawans", FormMethod.Post, new { @class = "form-horizontal" }))

            {
                <fieldset>
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.NIP)

                    <div class="form-group">
                        @Html.LabelFor(model => model.DivisiID, htmlAttributes: new { @class = "control-label" })
                        <div class="controls">
                            @Html.DropDownList("DivisiID", null, htmlAttributes: new { @class = "span6 typeahead" })
                            @Html.ValidationMessageFor(model => model.DivisiID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Nama, htmlAttributes: new { @class = "control-label" })
                        <div class="controls">
                            @Html.EditorFor(model => model.Nama, new { htmlAttributes = new { @class = "span6 typeahead" } })
                            @Html.ValidationMessageFor(model => model.Nama, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Alamat, htmlAttributes: new { @class = "control-label" })
                        <div class="controls">
                            @Html.EditorFor(model => model.Alamat, new { htmlAttributes = new { @class = "span6 typeahead" } })
                            @Html.ValidationMessageFor(model => model.Alamat, "", new { @class = "text-danger" })
                        </div>
                    </div>
                   
                    <div class="form-group">
                        @Html.LabelFor(model => model.TanggalLahir, htmlAttributes: new { @class = "control-label" })
                        <div class="controls">
                            @Html.EditorFor(model => model.TanggalLahir, new { htmlAttributes = new {  @class = "input-xlarge datepicker"} })
                            @Html.ValidationMessageFor(model => model.TanggalLahir, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    
                    <div class="form-actions">

                        <button type="submit" class="btn btn-primary">
                            Update
                        </button>

                    </div>
                </fieldset>
            }

            <!--sampai sini-->

        </div>
    </div>
</div>
@*
    @{
        ViewBag.Title = "Edit";
    }

    <h2>Edit</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Karyawan</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.NIP)

            <div class="form-group">
                @Html.LabelFor(model => model.DivisiID, "DivisiID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("DivisiID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DivisiID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Nama, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nama, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nama, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Alamat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Alamat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Alamat, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TanggalLahir, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TanggalLahir, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TanggalLahir, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

*@