ASPNET.MVC.UntukPemula/Pegawai.Web/Controllers/DivisisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Pegawai.Web.Models;

namespace Pegawai.Web.Controllers //ini nama sebuah controller 
{
    public class DivisisController : Controller // ini adalah sebuah controller yang akan di tampilkan di sebuah form divisi, jika dalam vb.net di sebut divs\isi.vb
    {
        private PegawaiDBEntities db = new PegawaiDBEntities();
        // di atas adalah sebuah conection database di pemograman jika di vb kita suka panggail dengan call konek() / memanggail str konekis
        // dalam contoh disini str nya adalah PegawaiDBEntitie

        // GET: Divisis
        [Authorize(Roles = "Admin, Pimpinan")]
        public ActionResult Index() // di vb biasa di sub event sub, saya biasa di vb dengan memanggil sub tampil()/ sub mulai()
        {
            return View(db.Divisis.ToList()); 
            //sintak ini adala perintah untuk menampilkan (View) database/db PegawaiDBEntitie dengan table bernama divisi
        }

        // GET: Divisis/Details/5
        [Authorize(Roles = "Admin, Pimpinan")]
        public ActionResult Details(int? id)
        //aksi ini menampiklan event/tombol detail dalam vb saya biasa gunakan sub tampil()
        {
            if (id == null) //jika id tidak ada maka akan muncul error "bad request"
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Divisi divisi = db.Divisis.Find(id); 
            //jika di temukan maka akan memanggil table divisi dari database jika id yang di cari tidak ada maka akan ada info form tidak ada
            if (divisi == null)
            {
                return HttpNotFound();
            }
            return View(divisi);//table divisi
            //jika di temukan maka akan di tampilkan /divisi/details/id
        }

        // GET: Divisis/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        //ketika mengklik tombol create maka akan muncul form create
        {
            return View();
        }

        // POST: Divisis/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "DivisiID,NamaDivisi")] Divisi divisi)
        //ini adalah event simpan jika di vb 
        //"Private Sub bsimpan_Click_1(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles bsimpan.Click"
        {
            if (ModelState.IsValid)
            //setelah kita input di form dan apa yang di inginkan oleh model yang kita buat misal ada format tanggal yyyy/mm/dd 
            //terus kita input format tanggal dengan mm/dd/yyyy maka model state akan menginformasika ada kesalahan atau error dan 
            // akan form akan tetap di form create "return View(divisi);" sampai inputan sesuai yang di ingin kan oleh model

            {
                
                db.Divisis.Add(divisi);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(divisi);
        }

        // GET: Divisis/Edit/5
        [Authorize(Roles = "Admin, Pimpinan")]
        public ActionResult Edit(int? id)//peritah edit sama dengan pertintah detail, cuma saja perbedaannya di form / view
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Divisi divisi = db.Divisis.Find(id);
            if (divisi == null)
            {
                return HttpNotFound();
            }
            return View(divisi);
        }

        // POST: Divisis/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Pimpinan")]
        public ActionResult Edit([Bind(Include = "DivisiID,NamaDivisi")] Divisi divisi)
        {
            if (ModelState.IsValid)
            {
                db.Entry(divisi).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(divisi);
            
        }

        // GET: Divisis/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Divisi divisi = db.Divisis.Find(id);
            if (divisi == null)
            {
                return HttpNotFound();
            }
            return View(divisi);
        }

        // POST: Divisis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Divisi divisi = db.Divisis.Find(id);
            db.Divisis.Remove(divisi);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ASPNET.MVC.UntukPemula/Pegawai.Web/Controllers/MetroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pegawai.Web.Controllers
{
    public class MetroController : Controller
    {
        // GET: Metro
        
        public ActionResult Index()
        {
            ViewBag.Title = "Cing";
            return View();
        }
        // Get : User interface
        public ActionResult UI()
        {
            return View();
        }
        // Get : form
        public ActionResult Forms()
        {
            return View();
        }

        // Get : gambar
        public ActionResult Charts()
        {
            return View();
        }

        // Get : tabel
        public ActionResult Tables()
        {
            return View();
        }
        // Get : Latihan
        public ActionResult Latihan()
        {
            return View();
        }

        //post latihan
        [HttpPost]
        public ActionResult Latihan(string TextBoxNama, string TextAreaAlamat, string DropdownlistPropinsi, string RadioButtonKelamin, bool CeckBCSharp,
            bool CeckBJava, bool CeckBPhyton, IEnumerable<string> listBoxPekerjaan)
        {
            string languages = string.Empty;
            string jobs = string.Empty;
            if (CeckBCSharp)
            {
                languages = "C#" + "" + languages;

            }

            if (CeckBJava)
            {
                languages = "JAVA" + "" + languages;
            }
            if (CeckBPhyton)
            {
                languages = "PHYTON" + "" + languages;
            }
            foreach (string job in listBoxPekerjaan)
            {
                if (job.Equals("1"))
                {
                    jobs = "Programmer " + jobs;
                }
                else if
                      (job.Equals("2"))
                {
                    jobs = "Analis Sistem " + jobs;
                }
                else if
                     (job.Equals("3"))
                {
                    jobs = "Manager Projek " + jobs;
                }
                else
                {
                    jobs = "Programmer " + jobs;
                }
            }

            ViewBag.Hasil = "Nama = " + TextBoxNama + " , Alamat = " + TextAreaAlamat + " , Propinsi = " + DropdownlistPropinsi + " , Jenis kelamin = " +
                RadioButtonKelamin + " , Bahasa Pemograman = " + languages + " , Pengalaman Kerja = " + jobs;

            return View();
        }


        public ActionResult Tes()
        {
            return View();
        }
        public ActionResult Tos()
        {
            return View();
        }
    }
}

ASPNET.MVC.UntukPemula/Pegawai.Web/Views/Metro/Charts.cshtml
@{
    ViewBag.Title = "Charts";
    Layout = "~/Views/Shared/Master_Layout.cshtml";
}

<h2>Charts</h2>

ASPNET.MVC.UntukPemula/Pegawai.Web/Views/Metro/Forms.cshtml
@{
    ViewBag.Title = "Forms";
    Layout = "~/Views/Shared/Master_Layout.cshtml";
}

<h2>Forms</h2>

ASPNET.MVC.UntukPemula/Pegawai.Web/Views/Metro/Latihan.cshtml
@{
    ViewBag.Title = "Latihan";
    Layout = "~/Views/Shared/Master_Layout.cshtml";
}

<!--@using (Html.BeginForm("Latihan", "Metro", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.Label("TextBoxNama", "Nama", new { @class = "control-label" })
    @Html.TextBox("TextBoxNama", "Nama", new { @class = "span6 typeahead" })

}


    @Html.ActionLink("Divisi", "Index","Divisis")
    -->

<div class="row-fluid sortable">

    <div class="box span12"> <!--membuat box--> 
        <div class="box-header" data-original-title> 
            <!--membuat box header dengan nama Form latihan dan dengan icon edit
            <i class="halflings-icon glyphicon-edit"></i><span class="break"></span>Form Latihan -->
            <h2>
                <i class="halflings-icon edit"></i><span class="break"></span>Form Latihan
            </h2>
            
            <div class="box-icon">
                <a href="#" class="btn-setting">
                    <i class="halflings-icon wrench"></i>
                </a>
                <a href="#" class="btn-minimize">
                    <i class="halflings-icon chevron-up"></i>
                </a>
                <a href="#" class="btn-close">
                    <i class="halflings-icon remove"></i>
                </a>
            </div>
        
        </div>

        <div class="box-content"><!--ini adalah akan box untuk isi content -->
            @using (Html.BeginForm("Latihan", "Metro", FormMethod.Post, new { @class = "form-horizontal" }))
 {

                <fieldset>
                    @ViewBag.Hasil
                    <div class="control-group">
                            @Html.Label("TextBoxNama", "Nama", new { @class = "control-label" })
                        
                        <div class="controls">
                            @Html.TextBox("TextBoxNama", string.Empty, new { @class = "span6 typeahead" })
                        </div>
                    </div>

                    <div class="control-group">
                        @Html.Label("TextBoxNama", "Alamat", new { @class = "control-label" })
                        <div class="controls">
                            <!--@Html.TextArea("TextAreaAlamat", string.Empty, new { @row="5",@class = "span6 typeahead" })-->
                            @Html.TextArea("TextAreaAlamat", string.Empty, new { @class = "cleditor" })
                            <!--text area dengan kondis text kosong dan bentuk seperti notepade-->
                        </div>
                    </div>
                    
                    <div class="control-group">
                        @Html.Label("TextBoxNama", "Propinsi", new { @class = "control-label" })
                        <!--label dengan nama propinsi-->
                        <div class="controls">
                            <!-- @Html.DropDownList("DropdownlistPropinsi", new SelectList(new List<Object>
                             {
                             new { value="KALSEL",text ="Kalimantan Selatan" },
                            new { value="JABAR",text ="Jawa Barat" }
                                                     },"value","text",2),"Pilih Propinsi")-->
                            <!--drop down dengan value dropdownlistpropinsi-- dengan list kalimantan...-->
                            @Html.DropDownList("DropdownlistPropinsi", new SelectList(new List<Object>
                              {
                                new { value="KALSEL",text ="Kalimantan Selatan" },
                                new { value="JABAR",text ="Jawa Barat" },
                                new { value="JABAR",text ="Jawa Tengah" },
                                new { value="JABAR",text ="Jawa Timur" }
                               }, 
                               "value", "text", 2), 
                               "Pilih Propinsi", new { @data_rel = "chosen" })
                        </div>
                    </div>
                    
                    <div class="control-group">
                        @Html.Label("RadioButtonKelamin", "Jenis Kelamin", new { @class = "control-label" })
                        
                        <div class="controls">
                            <label class="radio">
                                @Html.RadioButton("RadioButtonKelamin", "Laki-laki") Laki-laki
                                <!--radio button-->
                            </label>
                            <div style="clear:both"></div> 
                            <label class="radio">
                                @Html.RadioButton("RadioButtonKelamin", "Perempuan") Perempuan
                            </label>
                        
                        </div>
                    </div>
                    
                    <div class="control-group">
                        @Html.Label("TextBoxNama", "Pilih Bahasa", new { @class = "control-label" })
                        <div class="controls">
                            @Html.CheckBox("CeckBCSharp") C#
                            @Html.CheckBox("CeckBJava") Java
                            @Html.CheckBox("CeckBPhyton") Phyton
                        </div>
                    </div>
                    
                    <div class="control-group">
                        @Html.Label("TextBoxNama", "Pengalaman Kerja", new { @class = "control-label" })
                        <div class="controls">
                            @Html.ListBox("listBoxPekerjaan", new SelectList(new List<Object>{
                                new {value='1', text="Programmer"},
                                new {value='2', text="Analis Sistem"},
                                new {value='3', text="Administrator Database"},
                                new {value='4', text="Manajer Projek"},
                                    }, "value", "text", 2), new { @data_rel = "chosen" })
                        </div>
                    </div>
                    
                    
                    
                    <div class="controls">
                        <button type="submit" class="btn-primary">simpan</button>
                        <button type="reset" class="btn">Batal</button>
                    </div>

                </fieldset>
            }
        </div>


    </div>




</div>

ASPNET.MVC.UntukPemula/Pegawai.Web/Views/Metro/Tables.cshtml
@{
    ViewBag.Title = "Tables";
    Layout = "~/Views/Shared/Master_Layout.cshtml";
}

<h2>Tables</h2>

ASPNET.MVC.UntukPemula/Pegawai.Web/Views/Metro/Tes.cshtml
@{
    ViewBag.Title = "Tes";
    Layout = "~/Views/Shared/Master_Layout.cshtml";
}

<h2>Tes</h2>

ASPNET.MVC.UntukPemula/Pegawai.Web/Views/Metro/Tos.cshtml
@{
    ViewBag.Title = "Tos";
}

<h2>Tos</h2>

ASPNET.MVC.UntukPemula/Pegawai.Web/Views/Metro/UI.cshtml
@{
    ViewBag.Title = "UI";
    Layout = "~/Views/Shared/Master_Layout.cshtml";
}

<h2>UI</h2>