ASPNET.MVC.UntukPemula/Pegawai.Web/Controllers/RolesController.cs
/* Default Roles
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pegawai.Web.Controllers
{
    public class RolesController : Controller
    {
        // GET: Roles
        public ActionResult Index()
        {
            return View();
        }
    }
}
*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Pegawai.Web.Models;

namespace PengelolaanPegawai.Web.Controllers
{
    public class RolesController : Controller
    {
        private ApplicationDbContext context = new ApplicationDbContext();

        // GET: Roles
        public ActionResult Index()
        {
            var roles = context.Roles.ToList();
            return View(roles);
        }

        // GET: /Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                context.Roles.Add(new Microsoft.AspNet.Identity.EntityFramework.IdentityRole()
                {
                    Name = collection["RoleName"]
                });
                context.SaveChanges();
                ViewBag.ResultMessage = "Role created successfully !";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: /Roles/Edit/4
        public ActionResult Edit(string roleName)
        {
            var thisRole = context.Roles.Where(r => r.Name.Equals(roleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            return View(thisRole);
        }

        //
        // POST: /Roles/Edit/4
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Microsoft.AspNet.Identity.EntityFramework.IdentityRole role)
        {
            try
            {
                context.Entry(role).State = System.Data.Entity.EntityState.Modified;
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: /Roles/Get/4
        public ActionResult Delete(string RoleName)
        {
            var thisRole = context.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            context.Roles.Remove(thisRole);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ASPNET.MVC.UntukPemula/Pegawai.Web/Views/Roles/Create.cshtml
@{
    ViewBag.Title = "Manajemen Role";
}

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon align-justify"></i><span class="break"></span><i class="halflings-icon th-list"></i>@Html.ActionLink("kembali", "Index")</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            @using (Html.BeginForm("Create", "Roles", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <fieldset>
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="control-group">
                        @Html.Label("Nama Role", htmlAttributes: new { @class = "control-label" })
                        <div class="controls">
                            @Html.TextBox("RoleName", "", new { htmlAttributes = new { @class = "span6 typeahead" } })
                        </div>
                    </div>

                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </fieldset>
            }
        </div>
    </div>
</div>


@*
        @{
        ViewBag.Title = "Create";
    }

    <h2>Create</h2>

*@

ASPNET.MVC.UntukPemula/Pegawai.Web/Views/Roles/Edit.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole
@{
    ViewBag.Title = "Manajemen Role";
}

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon align-justify"></i><span class="break"></span><i class="halflings-icon th-list"></i>@Html.ActionLink("kembali", "Index")</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            @using (Html.BeginForm("Edit", "Roles", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <fieldset>
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="control-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                        <div class="controls">
                            @Html.TextBoxFor(model => model.Name, "", new { htmlAttributes = new { @class = "span6 typeahead" } })
                        </div>
                    </div>

                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </fieldset>
            }
        </div>
    </div>
</div>

@*@{
        ViewBag.Title = "Edit";
    }

    <h2>Edit</h2>
*@

ASPNET.MVC.UntukPemula/Pegawai.Web/Views/Roles/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Manajemen Role";
}

<div class="row-fluid sortable">
    <div class="box span12" style="margin-left:0px">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon align-justify"></i><span class="break"></span><i class="halflings-icon plus"></i>@Html.ActionLink("tambah", "Create")</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <table class="table table-striped table-bordered bootstrap-datatable">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th></th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @*<a class="btn btn-success" href="@Url.Action("Details", new { id = item.Name })">
                                    <i class="halflings-icon white zoom-in"></i>
                                </a>*@
                            <a class="btn btn-info" href="@Url.Action("Edit", new { roleName = item.Name })">
                                <i class="halflings-icon white edit"></i>
                            </a>
                            <a class="btn btn-danger" href="~/Roles/Delete?RoleName=@item.Name">
                                <i class="halflings-icon white trash"></i>
                            </a>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>



@*@{
        ViewBag.Title = "Index";
    }

    <h2>Index</h2>
*@